name: SSM

defaults:
  - model: default_model
  - _self_

model:
  r2_dim: 8
  r_dim: 6

ssm_params:
  Nlds: 3
  n_disc_states: 2
  latent_dim: 2
  obs_dim: 3
  random_projection: true
  rand_dim: 20
  partial_sup: true
  full_sup: false
  overlap: 2
  normalize: true
  seed: 10
  time_bins_train: 200000
  time_bins_test: 50000
  timescales: [.1,1,10,100,1000,.5]
  z_timescale: [.975,.975,.975]

train:
  version: ${resolve_default:0,${...version}}
  num_epochs: 1000
  sequence_length: 1000
  overlap_factor: 10
  stack_inputs: true
  num_workers: 6
  save_summary_steps: 5
  show_progress: true
  show_inf_progress: false
  gpu: 0
  test: false
  batch_size_input: true
  batch_size: 32768

delay:
  delay_embed: false
  delay_tau: 3
  delay_pcs: true
  skipt: 15